### ISSUE TITLE
Anti-aliasing against transparent background

### ISSUE THREAD

**Issue by AlanRitchie** [cognitedata/reveal-viewer#14]
Edges where part of the model crosses another part of the model are fine, but edges where the grey model is showing against the background are picking up black and white pixels.

![image](https://user-images.githubusercontent.com/24223191/58116932-6d273200-7bf5-11e9-9f0b-82c398c564af.png)

We are using a transparent background for the viewer, so the background colour is the colour of the element behind the canvas.  It looks like the anti-aliasing isn't averaging the alpha value to make the edge pixels semi-transparent?

**Comment by anderscognite** [comment]
Thanks for reporting. Will take a look at alpha averaging.

**Comment by anderscognite** [comment]
I have changed so alpha is used during averaging. 

Before:
<img width="1792" alt="Screenshot 2019-05-31 18 34 04" src="https://user-images.githubusercontent.com/34239077/58721976-85a60200-83d6-11e9-8c20-ad0e4d5c968f.png">

After:
<img width="1792" alt="Screenshot 2019-05-31 18 33 43" src="https://user-images.githubusercontent.com/34239077/58721971-8343a800-83d6-11e9-9647-3b6db78f99e1.png">

Will be released in 5.1.2 on Monday.

**Comment by AlanRitchie** [comment]
Looks much better, thanks
