### ISSUE TITLE
Pre-Defined Views of the 3D model

### ISSUE THREAD

**Issue by paulobotura** [cognitedata/reveal-viewer#2]
Suggestion done by Lundin during AvevaNet workshop. 
To have pre-defined views of the 3D model accessed by a "button". Eg. "Centered", "Mid Sliced", "Far Standard view", "User Set view 1, 2, 3, etc"

**Comment by anderscognite** [comment]
This is something that should be implemented in i.e. OpSup, and not in the 3d viewer component. Possibly a backend for this, but not sure. @f2cognite does it make any sense to have this in the backend?

**Comment by ghost** [comment]
This is something to take into consideration for the future, but I think the immediate way forward is to delegate the responsibility of this to the application the viewer runs in. It might make sense to have this in the 3D backend, but I think we would need to take into consideration how it would interact e.g. when composing multiple models into a single digital twin.

**Comment by paulobotura** [comment]
@cathrinestenstadvold would you consider adding this on OpSup Roadmap?

**Comment by cathrinestenstadvold** [comment]
Sorry for the late response! This might be something that we will add going forward, but it´s not on our  roadmap for the upcoming months. This can change if you have some input that will increase the priority.

**Comment by anderscognite** [comment]
I think we will close this for now.
