### ISSUE TITLE
Users to be able to add Markups on the 3D model if an error is found

### ISSUE THREAD

**Issue by paulobotura** [cognitedata/reveal-viewer#4]
User should be able to add a comment on the 3D model if he/she detects an error/inconsistency on the 3D model.

**Comment by anderscognite** [comment]
This sounds relevant for another application _using_ the 3d viewer.

**Comment by anderscognite** [comment]
I will refer to this issue once we have a place for that.

**Comment by anderscognite** [comment]
We have no plan of implementing this in the viewer specifically, but will be possible in applications.

I have created an issue in our digital twin explorer app: https://github.com/cognitedata/digital-twin-explorer/issues/1
