### ISSUE TITLE
Cognite3DViewer.dispose() function causes js-errors

### ISSUE THREAD

**Issue by ragnhildlarsen** [cognitedata/reveal-viewer#6]
Cognite3DViewer.dispose() is called when a component is removed from the DOM/when ngOnDestroy is called (Angular).

Navigating away from a 3D model before loading is finished causes js-errors in the console:
- `ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'redraw' of undefined`
![Screenshot 2019-05-07 at 09 04 20](https://user-images.githubusercontent.com/50363113/57293596-74165680-70c5-11e9-9af6-102be2eaf35e.png)
- `ERROR TypeError: Cannot read property 'enableKeyboardNavigation' of undefined`
![Screenshot 2019-05-07 at 09 11 31](https://user-images.githubusercontent.com/50363113/57293575-652fa400-70c5-11e9-9c6e-19eeb821be7d.png)
- `ERROR TypeError: Cannot read property 'setState' of undefined`
![Screenshot 2019-05-07 at 09 12 20](https://user-images.githubusercontent.com/50363113/57293553-5b0da580-70c5-11e9-8aad-9e348797c5d2.png)

'enableKeyboardNavigation' error appears when using the keyboard to navigate, e.g. by tabbing or by using the normal 3D viewer controls such as arrows/WASD.

**Comment by anderscognite** [comment]
These issues are fixed in 5.0.3. Thanks!

**Comment by anderscognite** [comment]
Not true! Forgot the `enableKeyboardNavigation` issue.
